# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.14-s082_1 on Tue Sep 03 14:58:42 IST 2024

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design AR_32

set_load -pin_load 0.15 [get_ports {k[63]}]
set_load -pin_load 0.15 [get_ports {k[62]}]
set_load -pin_load 0.15 [get_ports {k[61]}]
set_load -pin_load 0.15 [get_ports {k[60]}]
set_load -pin_load 0.15 [get_ports {k[59]}]
set_load -pin_load 0.15 [get_ports {k[58]}]
set_load -pin_load 0.15 [get_ports {k[57]}]
set_load -pin_load 0.15 [get_ports {k[56]}]
set_load -pin_load 0.15 [get_ports {k[55]}]
set_load -pin_load 0.15 [get_ports {k[54]}]
set_load -pin_load 0.15 [get_ports {k[53]}]
set_load -pin_load 0.15 [get_ports {k[52]}]
set_load -pin_load 0.15 [get_ports {k[51]}]
set_load -pin_load 0.15 [get_ports {k[50]}]
set_load -pin_load 0.15 [get_ports {k[49]}]
set_load -pin_load 0.15 [get_ports {k[48]}]
set_load -pin_load 0.15 [get_ports {k[47]}]
set_load -pin_load 0.15 [get_ports {k[46]}]
set_load -pin_load 0.15 [get_ports {k[45]}]
set_load -pin_load 0.15 [get_ports {k[44]}]
set_load -pin_load 0.15 [get_ports {k[43]}]
set_load -pin_load 0.15 [get_ports {k[42]}]
set_load -pin_load 0.15 [get_ports {k[41]}]
set_load -pin_load 0.15 [get_ports {k[40]}]
set_load -pin_load 0.15 [get_ports {k[39]}]
set_load -pin_load 0.15 [get_ports {k[38]}]
set_load -pin_load 0.15 [get_ports {k[37]}]
set_load -pin_load 0.15 [get_ports {k[36]}]
set_load -pin_load 0.15 [get_ports {k[35]}]
set_load -pin_load 0.15 [get_ports {k[34]}]
set_load -pin_load 0.15 [get_ports {k[33]}]
set_load -pin_load 0.15 [get_ports {k[32]}]
set_load -pin_load 0.15 [get_ports {k[31]}]
set_load -pin_load 0.15 [get_ports {k[30]}]
set_load -pin_load 0.15 [get_ports {k[29]}]
set_load -pin_load 0.15 [get_ports {k[28]}]
set_load -pin_load 0.15 [get_ports {k[27]}]
set_load -pin_load 0.15 [get_ports {k[26]}]
set_load -pin_load 0.15 [get_ports {k[25]}]
set_load -pin_load 0.15 [get_ports {k[24]}]
set_load -pin_load 0.15 [get_ports {k[23]}]
set_load -pin_load 0.15 [get_ports {k[22]}]
set_load -pin_load 0.15 [get_ports {k[21]}]
set_load -pin_load 0.15 [get_ports {k[20]}]
set_load -pin_load 0.15 [get_ports {k[19]}]
set_load -pin_load 0.15 [get_ports {k[18]}]
set_load -pin_load 0.15 [get_ports {k[17]}]
set_load -pin_load 0.15 [get_ports {k[16]}]
set_load -pin_load 0.15 [get_ports {k[15]}]
set_load -pin_load 0.15 [get_ports {k[14]}]
set_load -pin_load 0.15 [get_ports {k[13]}]
set_load -pin_load 0.15 [get_ports {k[12]}]
set_load -pin_load 0.15 [get_ports {k[11]}]
set_load -pin_load 0.15 [get_ports {k[10]}]
set_load -pin_load 0.15 [get_ports {k[9]}]
set_load -pin_load 0.15 [get_ports {k[8]}]
set_load -pin_load 0.15 [get_ports {k[7]}]
set_load -pin_load 0.15 [get_ports {k[6]}]
set_load -pin_load 0.15 [get_ports {k[5]}]
set_load -pin_load 0.15 [get_ports {k[4]}]
set_load -pin_load 0.15 [get_ports {k[3]}]
set_load -pin_load 0.15 [get_ports {k[2]}]
set_load -pin_load 0.15 [get_ports {k[1]}]
set_load -pin_load 0.15 [get_ports {k[0]}]
set_clock_gating_check -setup 0.0 
set_input_delay -add_delay -max 0.8 [get_ports {a[31]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[30]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[29]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[28]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[27]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[26]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[25]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[24]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[23]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[22]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[21]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[20]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[19]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[18]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[17]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[16]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[15]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[14]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[13]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[12]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[11]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[10]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[9]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[8]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[7]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[6]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[5]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[4]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[3]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[2]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[1]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[0]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[31]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[30]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[29]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[28]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[27]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[26]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[25]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[24]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[23]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[22]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[21]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[20]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[19]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[18]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[17]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[16]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[15]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[14]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[13]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[12]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[11]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[10]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[9]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[8]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[7]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[6]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[5]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[4]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[3]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[2]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[1]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[0]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[63]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[62]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[61]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[60]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[59]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[58]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[57]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[56]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[55]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[54]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[53]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[52]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[51]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[50]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[49]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[48]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[47]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[46]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[45]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[44]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[43]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[42]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[41]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[40]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[39]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[38]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[37]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[36]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[35]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[34]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[33]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[32]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[31]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[30]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[29]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[28]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[27]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[26]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[25]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[24]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[23]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[22]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[21]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[20]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[19]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[18]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[17]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[16]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[15]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[14]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[13]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[12]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[11]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[10]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[9]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[8]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[7]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[6]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[5]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[4]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[3]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[2]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[1]}]
set_output_delay -add_delay -max 0.8 [get_ports {k[0]}]
set_max_fanout 20.000 [current_design]
set_input_transition 0.12 [get_ports {a[31]}]
set_input_transition 0.12 [get_ports {a[30]}]
set_input_transition 0.12 [get_ports {a[29]}]
set_input_transition 0.12 [get_ports {a[28]}]
set_input_transition 0.12 [get_ports {a[27]}]
set_input_transition 0.12 [get_ports {a[26]}]
set_input_transition 0.12 [get_ports {a[25]}]
set_input_transition 0.12 [get_ports {a[24]}]
set_input_transition 0.12 [get_ports {a[23]}]
set_input_transition 0.12 [get_ports {a[22]}]
set_input_transition 0.12 [get_ports {a[21]}]
set_input_transition 0.12 [get_ports {a[20]}]
set_input_transition 0.12 [get_ports {a[19]}]
set_input_transition 0.12 [get_ports {a[18]}]
set_input_transition 0.12 [get_ports {a[17]}]
set_input_transition 0.12 [get_ports {a[16]}]
set_input_transition 0.12 [get_ports {a[15]}]
set_input_transition 0.12 [get_ports {a[14]}]
set_input_transition 0.12 [get_ports {a[13]}]
set_input_transition 0.12 [get_ports {a[12]}]
set_input_transition 0.12 [get_ports {a[11]}]
set_input_transition 0.12 [get_ports {a[10]}]
set_input_transition 0.12 [get_ports {a[9]}]
set_input_transition 0.12 [get_ports {a[8]}]
set_input_transition 0.12 [get_ports {a[7]}]
set_input_transition 0.12 [get_ports {a[6]}]
set_input_transition 0.12 [get_ports {a[5]}]
set_input_transition 0.12 [get_ports {a[4]}]
set_input_transition 0.12 [get_ports {a[3]}]
set_input_transition 0.12 [get_ports {a[2]}]
set_input_transition 0.12 [get_ports {a[1]}]
set_input_transition 0.12 [get_ports {a[0]}]
set_input_transition 0.12 [get_ports {b[31]}]
set_input_transition 0.12 [get_ports {b[30]}]
set_input_transition 0.12 [get_ports {b[29]}]
set_input_transition 0.12 [get_ports {b[28]}]
set_input_transition 0.12 [get_ports {b[27]}]
set_input_transition 0.12 [get_ports {b[26]}]
set_input_transition 0.12 [get_ports {b[25]}]
set_input_transition 0.12 [get_ports {b[24]}]
set_input_transition 0.12 [get_ports {b[23]}]
set_input_transition 0.12 [get_ports {b[22]}]
set_input_transition 0.12 [get_ports {b[21]}]
set_input_transition 0.12 [get_ports {b[20]}]
set_input_transition 0.12 [get_ports {b[19]}]
set_input_transition 0.12 [get_ports {b[18]}]
set_input_transition 0.12 [get_ports {b[17]}]
set_input_transition 0.12 [get_ports {b[16]}]
set_input_transition 0.12 [get_ports {b[15]}]
set_input_transition 0.12 [get_ports {b[14]}]
set_input_transition 0.12 [get_ports {b[13]}]
set_input_transition 0.12 [get_ports {b[12]}]
set_input_transition 0.12 [get_ports {b[11]}]
set_input_transition 0.12 [get_ports {b[10]}]
set_input_transition 0.12 [get_ports {b[9]}]
set_input_transition 0.12 [get_ports {b[8]}]
set_input_transition 0.12 [get_ports {b[7]}]
set_input_transition 0.12 [get_ports {b[6]}]
set_input_transition 0.12 [get_ports {b[5]}]
set_input_transition 0.12 [get_ports {b[4]}]
set_input_transition 0.12 [get_ports {b[3]}]
set_input_transition 0.12 [get_ports {b[2]}]
set_input_transition 0.12 [get_ports {b[1]}]
set_input_transition 0.12 [get_ports {b[0]}]
set_wire_load_mode "enclosed"
