/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID vlsilab01.nitdelhi.ac.in)
#  Generated on:      Tue Sep  3 15:05:26 2024
#  Design:            AR_8
#  Command:           saveNetlist AR_8pd.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Sep  3 2024 14:55:05 IST (Sep  3 2024 09:25:05 UTC)
// Verification Directory fv/AR_8 
module AR_8 (
	k, 
	a, 
	b);
   output [15:0] k;
   input [7:0] a;
   input [7:0] b;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_174;
   wire n_175;
   wire n_177;
   wire n_178;
   wire n_180;
   wire n_181;
   wire n_183;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_189;

   CLKXOR2X2 g3351__2398 (.A(n_189),
	.B(n_185),
	.Y(k[14]));
   XNOR2X1 g3353__5107 (.A(n_187),
	.B(n_186),
	.Y(n_189));
   OAI21X4 g3352__6260 (.A0(n_187),
	.A1(n_186),
	.B0(n_185),
	.Y(k[15]));
   CLKINVX2 g3354 (.A(n_183),
	.Y(k[13]));
   ADDFX1 g3355__4319 (.A(n_159),
	.B(n_102),
	.CI(n_180),
	.CO(n_186),
	.S(n_183));
   CLKINVX2 g3356 (.A(n_181),
	.Y(k[12]));
   ADDFX1 g3357__8428 (.A(n_156),
	.B(n_160),
	.CI(n_177),
	.CO(n_180),
	.S(n_181));
   CLKINVX2 g3358 (.A(n_178),
	.Y(k[11]));
   ADDFX1 g3359__5526 (.A(n_163),
	.B(n_157),
	.CI(n_174),
	.CO(n_177),
	.S(n_178));
   CLKINVX2 g3360 (.A(n_175),
	.Y(k[10]));
   ADDFX1 g3361__6783 (.A(n_164),
	.B(n_161),
	.CI(n_171),
	.CO(n_174),
	.S(n_175));
   CLKINVX2 g3362 (.A(n_172),
	.Y(k[9]));
   ADDFX1 g3363__3680 (.A(n_162),
	.B(n_158),
	.CI(n_170),
	.CO(n_171),
	.S(n_172));
   AOI21XL g3370__1617 (.A0(n_167),
	.A1(n_166),
	.B0(n_168),
	.Y(n_170));
   CLKXOR2X2 g3371__2802 (.A(n_135),
	.B(n_165),
	.Y(k[8]));
   AOI2BB1XL g3372__1705 (.A0N(n_167),
	.A1N(n_166),
	.B0(n_165),
	.Y(n_168));
   ADDFX1 g3366__5122 (.A(n_150),
	.B(n_7),
	.CI(n_153),
	.CO(n_163),
	.S(n_164));
   ADDFX1 g3367__8246 (.A(n_148),
	.B(n_31),
	.CI(n_151),
	.CO(n_161),
	.S(n_162));
   ADDFX1 g3364__7098 (.A(n_92),
	.B(n_13),
	.CI(n_154),
	.CO(n_159),
	.S(n_160));
   ADDFX1 g3374__6131 (.A(n_112),
	.B(n_33),
	.CI(n_149),
	.CO(n_158),
	.S(n_165));
   ADDFX1 g3365__1881 (.A(n_155),
	.B(n_10),
	.CI(n_152),
	.CO(n_156),
	.S(n_157));
   ADDFX1 g3368__5115 (.A(n_86),
	.B(n_44),
	.CI(n_142),
	.CO(n_154),
	.S(n_155));
   ADDFX1 g3369__7482 (.A(n_143),
	.B(n_2),
	.CI(n_146),
	.CO(n_152),
	.S(n_153));
   ADDFX1 g3373__4733 (.A(n_144),
	.B(n_8),
	.CI(n_147),
	.CO(n_150),
	.S(n_151));
   ADDFX1 g3376__6161 (.A(n_120),
	.B(n_37),
	.CI(n_145),
	.CO(n_148),
	.S(n_149));
   ADDFX1 g3377__9315 (.A(n_141),
	.B(n_19),
	.CI(n_138),
	.CO(n_146),
	.S(n_147));
   ADDFX1 g3378__9945 (.A(n_123),
	.B(n_30),
	.CI(n_139),
	.CO(n_144),
	.S(n_145));
   ADDFX1 g3375__2883 (.A(n_76),
	.B(n_3),
	.CI(n_140),
	.CO(n_142),
	.S(n_143));
   ADDFX1 g3379__2346 (.A(n_69),
	.B(n_29),
	.CI(n_136),
	.CO(n_140),
	.S(n_141));
   ADDFX1 g3380__1666 (.A(n_129),
	.B(n_47),
	.CI(n_137),
	.CO(n_138),
	.S(n_139));
   ADDFX1 g3381__7410 (.A(n_56),
	.B(n_24),
	.CI(n_131),
	.CO(n_136),
	.S(n_137));
   MXI2XL g3382__6417 (.A(n_167),
	.B(n_104),
	.S0(n_166),
	.Y(n_135));
   CLKXOR2X2 g3383__5477 (.A(n_133),
	.B(n_132),
	.Y(k[7]));
   NOR2XL g3384__2398 (.A(n_133),
	.B(n_132),
	.Y(n_166));
   ADDFX1 g3385__5107 (.A(n_127),
	.B(n_40),
	.CI(n_130),
	.CO(n_131),
	.S(n_132));
   ADDFX1 g3386__6260 (.A(n_122),
	.B(n_0),
	.CI(n_124),
	.CO(n_129),
	.S(n_130));
   CLKXOR2X2 g3387__4319 (.A(n_126),
	.B(n_125),
	.Y(k[6]));
   OR2X1 g3389__8428 (.A(n_126),
	.B(n_125),
	.Y(n_127));
   ADDFX1 g3388__5526 (.A(n_121),
	.B(n_32),
	.CI(n_118),
	.CO(n_123),
	.S(n_124));
   ADDFX1 g3390__6783 (.A(n_116),
	.B(n_36),
	.CI(n_119),
	.CO(n_122),
	.S(n_125));
   ADDFX1 g3391__3680 (.A(n_113),
	.B(n_42),
	.CI(n_110),
	.CO(n_120),
	.S(n_121));
   ADDFX1 g3392__1617 (.A(n_109),
	.B(n_9),
	.CI(n_111),
	.CO(n_118),
	.S(n_119));
   CLKXOR2X2 g3394__2802 (.A(n_115),
	.B(n_114),
	.Y(k[5]));
   OR2X1 g3396__1705 (.A(n_115),
	.B(n_114),
	.Y(n_116));
   ADDFX1 g3393__5122 (.A(n_103),
	.B(n_15),
	.CI(n_105),
	.CO(n_112),
	.S(n_113));
   ADDFX1 g3395__8246 (.A(n_106),
	.B(n_38),
	.CI(n_107),
	.CO(n_110),
	.S(n_111));
   ADDFX1 g3397__7098 (.A(n_100),
	.B(n_43),
	.CI(n_108),
	.CO(n_109),
	.S(n_114));
   ADDFX1 g3399__6131 (.A(n_97),
	.B(n_5),
	.CI(n_95),
	.CO(n_107),
	.S(n_108));
   ADDFX1 g3398__1881 (.A(n_94),
	.B(n_35),
	.CI(n_96),
	.CO(n_105),
	.S(n_106));
   INVXL g3404 (.A(n_104),
	.Y(n_167));
   ADDFX1 g3406__5115 (.A(n_12),
	.B(n_11),
	.CI(n_93),
	.CO(n_104),
	.S(n_103));
   ADDFX1 g3407__7482 (.A(n_23),
	.B(n_4),
	.CI(n_91),
	.CO(n_185),
	.S(n_102));
   CLKXOR2X2 g3400__4733 (.A(n_99),
	.B(n_98),
	.Y(k[4]));
   OR2X1 g3402__6161 (.A(n_99),
	.B(n_98),
	.Y(n_100));
   ADDFX1 g3401__9315 (.A(n_88),
	.B(n_34),
	.CI(n_89),
	.CO(n_96),
	.S(n_97));
   ADDFX1 g3403__9945 (.A(n_83),
	.B(n_16),
	.CI(n_90),
	.CO(n_95),
	.S(n_98));
   ADDFX1 g3408__2883 (.A(n_22),
	.B(n_14),
	.CI(n_87),
	.CO(n_93),
	.S(n_94));
   ADDFX1 g3410__2346 (.A(n_46),
	.B(n_28),
	.CI(n_85),
	.CO(n_91),
	.S(n_92));
   ADDFX1 g3405__1666 (.A(n_79),
	.B(n_6),
	.CI(n_80),
	.CO(n_89),
	.S(n_90));
   ADDFX1 g3414__7410 (.A(n_18),
	.B(n_27),
	.CI(n_78),
	.CO(n_87),
	.S(n_88));
   ADDFX1 g3415__6417 (.A(n_39),
	.B(n_20),
	.CI(n_75),
	.CO(n_85),
	.S(n_86));
   XNOR2X2 g3409__5477 (.A(n_81),
	.B(n_82),
	.Y(k[3]));
   NAND2BXL g3411__2398 (.AN(n_82),
	.B(n_81),
	.Y(n_83));
   INVXL g3412 (.A(n_77),
	.Y(n_80));
   ADDFX1 g3416__5107 (.A(n_41),
	.B(n_45),
	.CI(n_73),
	.CO(n_78),
	.S(n_79));
   ADDFX1 g3413__6260 (.A(n_66),
	.B(n_26),
	.CI(n_72),
	.CO(n_77),
	.S(n_81));
   ADDFX1 g3417__4319 (.A(n_1),
	.B(n_48),
	.CI(n_68),
	.CO(n_75),
	.S(n_76));
   CLKXOR2X2 g3419__8428 (.A(n_70),
	.B(n_71),
	.Y(k[2]));
   NOR2XL g3418__5526 (.A(n_61),
	.B(n_67),
	.Y(n_73));
   NOR2XL g3421__6783 (.A(n_71),
	.B(n_70),
	.Y(n_72));
   ADDFX1 g3420__3680 (.A(n_17),
	.B(n_21),
	.CI(n_53),
	.CO(n_68),
	.S(n_69));
   AOI21XL g3422__1617 (.A0(n_57),
	.A1(n_65),
	.B0(n_58),
	.Y(n_67));
   CLKXOR2X1 g3423__2802 (.A(n_65),
	.B(n_59),
	.Y(n_66));
   AOI21XL g3424__1705 (.A0(n_63),
	.A1(n_62),
	.B0(n_64),
	.Y(n_70));
   NOR2XL g3426__5122 (.A(n_63),
	.B(n_62),
	.Y(n_64));
   NOR2XL g3425__8246 (.A(n_61),
	.B(n_63),
	.Y(n_65));
   AOI21X4 g3427__7098 (.A0(n_54),
	.A1(n_55),
	.B0(n_63),
	.Y(k[1]));
   XNOR2X1 g3429__6131 (.A(n_58),
	.B(n_57),
	.Y(n_59));
   XNOR2X1 g3430__1881 (.A(n_52),
	.B(n_51),
	.Y(n_56));
   XNOR2X1 g3428__5115 (.A(n_50),
	.B(n_49),
	.Y(n_62));
   NOR2XL g3431__7482 (.A(n_55),
	.B(n_54),
	.Y(n_63));
   OR2X1 g3433__4733 (.A(n_52),
	.B(n_51),
	.Y(n_53));
   NOR2XL g3432__6161 (.A(n_50),
	.B(n_49),
	.Y(n_61));
   NAND2XL g3488__9315 (.A(b[7]),
	.B(a[3]),
	.Y(n_48));
   NAND2XL g3463__9945 (.A(b[3]),
	.B(a[5]),
	.Y(n_47));
   NAND2XL g3473__2883 (.A(b[5]),
	.B(a[7]),
	.Y(n_46));
   NAND2XL g3482__2346 (.A(b[4]),
	.B(a[0]),
	.Y(n_45));
   NAND2XL g3449__1666 (.A(b[5]),
	.B(a[6]),
	.Y(n_44));
   NAND2XL g3481__7410 (.A(b[1]),
	.B(a[4]),
	.Y(n_43));
   NAND2XL g3457__6417 (.A(b[4]),
	.B(a[3]),
	.Y(n_42));
   NAND2XL g3446__5477 (.A(b[3]),
	.B(a[1]),
	.Y(n_41));
   NAND2XL g3458__2398 (.A(b[1]),
	.B(a[6]),
	.Y(n_40));
   NAND2XL g3445__5107 (.A(b[4]),
	.B(a[7]),
	.Y(n_39));
   NAND2XL g3487__6260 (.A(b[3]),
	.B(a[3]),
	.Y(n_38));
   NAND2XL g3453__4319 (.A(b[5]),
	.B(a[3]),
	.Y(n_37));
   NAND2XL g3494__8428 (.A(b[1]),
	.B(a[5]),
	.Y(n_36));
   NAND2XL g3462__5526 (.A(b[4]),
	.B(a[2]),
	.Y(n_35));
   NAND2XL g3448__6783 (.A(b[3]),
	.B(a[2]),
	.Y(n_34));
   NAND2XL g3492__3680 (.A(b[6]),
	.B(a[2]),
	.Y(n_33));
   NAND2XL g3493__1617 (.A(b[3]),
	.B(a[4]),
	.Y(n_32));
   NAND2XL g3456__2802 (.A(b[6]),
	.B(a[3]),
	.Y(n_31));
   NAND2XL g3447__1705 (.A(b[4]),
	.B(a[4]),
	.Y(n_30));
   NAND2XL g3450__5122 (.A(b[3]),
	.B(a[6]),
	.Y(n_29));
   NAND2XL g3452__8246 (.A(b[7]),
	.B(a[5]),
	.Y(n_28));
   NAND2XL g3454__7098 (.A(b[5]),
	.B(a[0]),
	.Y(n_27));
   NAND2XL g3466__6131 (.A(b[1]),
	.B(a[0]),
	.Y(n_55));
   NAND2XL g3437__1881 (.A(b[3]),
	.B(a[0]),
	.Y(n_58));
   NAND2XL g3441__5115 (.A(b[0]),
	.B(a[6]),
	.Y(n_126));
   NAND2XL g3442__7482 (.A(b[0]),
	.B(a[7]),
	.Y(n_133));
   NAND2XL g3438__4733 (.A(b[2]),
	.B(a[1]),
	.Y(n_57));
   NAND2XL g3467__6161 (.A(b[1]),
	.B(a[7]),
	.Y(n_51));
   NAND2XL g3436__9315 (.A(b[0]),
	.B(a[2]),
	.Y(n_71));
   NAND2XL g3440__9945 (.A(b[7]),
	.B(a[1]),
	.Y(n_52));
   NAND2XL g3468__2883 (.A(b[2]),
	.B(a[0]),
	.Y(n_50));
   NAND2XL g3435__2346 (.A(b[0]),
	.B(a[1]),
	.Y(n_54));
   AND2X1 g3485__1666 (.A(b[1]),
	.B(a[2]),
	.Y(n_26));
   AND2X2 g3434__7410 (.A(b[0]),
	.B(a[0]),
	.Y(k[0]));
   NAND2XL g3460__6417 (.A(b[2]),
	.B(a[6]),
	.Y(n_24));
   NAND2XL g3480__5477 (.A(b[6]),
	.B(a[7]),
	.Y(n_23));
   NAND2XL g3464__2398 (.A(b[5]),
	.B(a[1]),
	.Y(n_22));
   NAND2XL g3477__5107 (.A(b[7]),
	.B(a[2]),
	.Y(n_21));
   NAND2XL g3490__6260 (.A(b[7]),
	.B(a[4]),
	.Y(n_20));
   NAND2XL g3497__4319 (.A(b[4]),
	.B(a[5]),
	.Y(n_19));
   NAND2XL g3461__8428 (.A(b[4]),
	.B(a[1]),
	.Y(n_18));
   NAND2XL g3472__5526 (.A(b[2]),
	.B(a[7]),
	.Y(n_17));
   NAND2XL g3474__6783 (.A(b[1]),
	.B(a[3]),
	.Y(n_16));
   NAND2XL g3484__3680 (.A(b[5]),
	.B(a[2]),
	.Y(n_15));
   NAND2XL g3483__1617 (.A(b[6]),
	.B(a[0]),
	.Y(n_14));
   NAND2XL g3495__2802 (.A(b[6]),
	.B(a[6]),
	.Y(n_13));
   NAND2XL g3475__1705 (.A(b[6]),
	.B(a[1]),
	.Y(n_12));
   NAND2XL g3455__5122 (.A(b[7]),
	.B(a[0]),
	.Y(n_11));
   NAND2XL g3478__8246 (.A(b[6]),
	.B(a[5]),
	.Y(n_10));
   NAND2XL g3491__7098 (.A(b[2]),
	.B(a[4]),
	.Y(n_9));
   NAND2XL g3476__6131 (.A(b[5]),
	.B(a[4]),
	.Y(n_8));
   NAND2XL g3496__1881 (.A(b[6]),
	.B(a[4]),
	.Y(n_7));
   NAND2XL g3459__5115 (.A(b[2]),
	.B(a[2]),
	.Y(n_6));
   NAND2XL g3489__7482 (.A(b[2]),
	.B(a[3]),
	.Y(n_5));
   NAND2XL g3486__4733 (.A(b[7]),
	.B(a[6]),
	.Y(n_4));
   NAND2XL g3465__6161 (.A(b[4]),
	.B(a[6]),
	.Y(n_3));
   NAND2XL g3444__9315 (.A(b[5]),
	.B(a[5]),
	.Y(n_2));
   NAND2XL g3479__9945 (.A(b[3]),
	.B(a[7]),
	.Y(n_1));
   NAND2XL g3451__2883 (.A(b[2]),
	.B(a[5]),
	.Y(n_0));
   NAND2XL g3439__2346 (.A(b[0]),
	.B(a[5]),
	.Y(n_115));
   NAND2XL g3443__1666 (.A(b[1]),
	.B(a[1]),
	.Y(n_49));
   NAND2XL g3470__7410 (.A(b[0]),
	.B(a[3]),
	.Y(n_82));
   NAND2XL g3469__6417 (.A(b[0]),
	.B(a[4]),
	.Y(n_99));
   NAND2XL g3471__5477 (.A(b[7]),
	.B(a[7]),
	.Y(n_187));
endmodule

