# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.14-s082_1 on Tue Sep 03 10:28:15 IST 2024

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design WA_32

set_load -pin_load 0.15 [get_ports {z[64]}]
set_load -pin_load 0.15 [get_ports {z[63]}]
set_load -pin_load 0.15 [get_ports {z[62]}]
set_load -pin_load 0.15 [get_ports {z[61]}]
set_load -pin_load 0.15 [get_ports {z[60]}]
set_load -pin_load 0.15 [get_ports {z[59]}]
set_load -pin_load 0.15 [get_ports {z[58]}]
set_load -pin_load 0.15 [get_ports {z[57]}]
set_load -pin_load 0.15 [get_ports {z[56]}]
set_load -pin_load 0.15 [get_ports {z[55]}]
set_load -pin_load 0.15 [get_ports {z[54]}]
set_load -pin_load 0.15 [get_ports {z[53]}]
set_load -pin_load 0.15 [get_ports {z[52]}]
set_load -pin_load 0.15 [get_ports {z[51]}]
set_load -pin_load 0.15 [get_ports {z[50]}]
set_load -pin_load 0.15 [get_ports {z[49]}]
set_load -pin_load 0.15 [get_ports {z[48]}]
set_load -pin_load 0.15 [get_ports {z[47]}]
set_load -pin_load 0.15 [get_ports {z[46]}]
set_load -pin_load 0.15 [get_ports {z[45]}]
set_load -pin_load 0.15 [get_ports {z[44]}]
set_load -pin_load 0.15 [get_ports {z[43]}]
set_load -pin_load 0.15 [get_ports {z[42]}]
set_load -pin_load 0.15 [get_ports {z[41]}]
set_load -pin_load 0.15 [get_ports {z[40]}]
set_load -pin_load 0.15 [get_ports {z[39]}]
set_load -pin_load 0.15 [get_ports {z[38]}]
set_load -pin_load 0.15 [get_ports {z[37]}]
set_load -pin_load 0.15 [get_ports {z[36]}]
set_load -pin_load 0.15 [get_ports {z[35]}]
set_load -pin_load 0.15 [get_ports {z[34]}]
set_load -pin_load 0.15 [get_ports {z[33]}]
set_load -pin_load 0.15 [get_ports {z[32]}]
set_load -pin_load 0.15 [get_ports {z[31]}]
set_load -pin_load 0.15 [get_ports {z[30]}]
set_load -pin_load 0.15 [get_ports {z[29]}]
set_load -pin_load 0.15 [get_ports {z[28]}]
set_load -pin_load 0.15 [get_ports {z[27]}]
set_load -pin_load 0.15 [get_ports {z[26]}]
set_load -pin_load 0.15 [get_ports {z[25]}]
set_load -pin_load 0.15 [get_ports {z[24]}]
set_load -pin_load 0.15 [get_ports {z[23]}]
set_load -pin_load 0.15 [get_ports {z[22]}]
set_load -pin_load 0.15 [get_ports {z[21]}]
set_load -pin_load 0.15 [get_ports {z[20]}]
set_load -pin_load 0.15 [get_ports {z[19]}]
set_load -pin_load 0.15 [get_ports {z[18]}]
set_load -pin_load 0.15 [get_ports {z[17]}]
set_load -pin_load 0.15 [get_ports {z[16]}]
set_load -pin_load 0.15 [get_ports {z[15]}]
set_load -pin_load 0.15 [get_ports {z[14]}]
set_load -pin_load 0.15 [get_ports {z[13]}]
set_load -pin_load 0.15 [get_ports {z[12]}]
set_load -pin_load 0.15 [get_ports {z[11]}]
set_load -pin_load 0.15 [get_ports {z[10]}]
set_load -pin_load 0.15 [get_ports {z[9]}]
set_load -pin_load 0.15 [get_ports {z[8]}]
set_load -pin_load 0.15 [get_ports {z[7]}]
set_load -pin_load 0.15 [get_ports {z[6]}]
set_load -pin_load 0.15 [get_ports {z[5]}]
set_load -pin_load 0.15 [get_ports {z[4]}]
set_load -pin_load 0.15 [get_ports {z[3]}]
set_load -pin_load 0.15 [get_ports {z[2]}]
set_load -pin_load 0.15 [get_ports {z[1]}]
set_load -pin_load 0.15 [get_ports {z[0]}]
set_clock_gating_check -setup 0.0 
set_input_delay -add_delay -max 0.8 [get_ports {x[31]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[30]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[29]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[28]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[27]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[26]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[25]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[24]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[23]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[22]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[21]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[20]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[19]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[18]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[17]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[16]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[15]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[14]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[13]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[12]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[11]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[10]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[9]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[8]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[7]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[6]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[5]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[4]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[3]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[2]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[1]}]
set_input_delay -add_delay -max 0.8 [get_ports {x[0]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[31]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[30]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[29]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[28]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[27]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[26]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[25]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[24]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[23]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[22]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[21]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[20]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[19]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[18]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[17]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[16]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[15]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[14]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[13]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[12]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[11]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[10]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[9]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[8]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[7]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[6]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[5]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[4]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[3]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[2]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[1]}]
set_input_delay -add_delay -max 0.8 [get_ports {y[0]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[64]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[63]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[62]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[61]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[60]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[59]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[58]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[57]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[56]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[55]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[54]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[53]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[52]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[51]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[50]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[49]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[48]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[47]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[46]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[45]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[44]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[43]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[42]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[41]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[40]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[39]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[38]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[37]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[36]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[35]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[34]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[33]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[32]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[31]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[30]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[29]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[28]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[27]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[26]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[25]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[24]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[23]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[22]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[21]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[20]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[19]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[18]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[17]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[16]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[15]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[14]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[13]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[12]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[11]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[10]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[9]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[8]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[7]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[6]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[5]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[4]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[3]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[2]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[1]}]
set_output_delay -add_delay -max 0.8 [get_ports {z[0]}]
set_max_fanout 20.000 [current_design]
set_input_transition 0.12 [get_ports {x[31]}]
set_input_transition 0.12 [get_ports {x[30]}]
set_input_transition 0.12 [get_ports {x[29]}]
set_input_transition 0.12 [get_ports {x[28]}]
set_input_transition 0.12 [get_ports {x[27]}]
set_input_transition 0.12 [get_ports {x[26]}]
set_input_transition 0.12 [get_ports {x[25]}]
set_input_transition 0.12 [get_ports {x[24]}]
set_input_transition 0.12 [get_ports {x[23]}]
set_input_transition 0.12 [get_ports {x[22]}]
set_input_transition 0.12 [get_ports {x[21]}]
set_input_transition 0.12 [get_ports {x[20]}]
set_input_transition 0.12 [get_ports {x[19]}]
set_input_transition 0.12 [get_ports {x[18]}]
set_input_transition 0.12 [get_ports {x[17]}]
set_input_transition 0.12 [get_ports {x[16]}]
set_input_transition 0.12 [get_ports {x[15]}]
set_input_transition 0.12 [get_ports {x[14]}]
set_input_transition 0.12 [get_ports {x[13]}]
set_input_transition 0.12 [get_ports {x[12]}]
set_input_transition 0.12 [get_ports {x[11]}]
set_input_transition 0.12 [get_ports {x[10]}]
set_input_transition 0.12 [get_ports {x[9]}]
set_input_transition 0.12 [get_ports {x[8]}]
set_input_transition 0.12 [get_ports {x[7]}]
set_input_transition 0.12 [get_ports {x[6]}]
set_input_transition 0.12 [get_ports {x[5]}]
set_input_transition 0.12 [get_ports {x[4]}]
set_input_transition 0.12 [get_ports {x[3]}]
set_input_transition 0.12 [get_ports {x[2]}]
set_input_transition 0.12 [get_ports {x[1]}]
set_input_transition 0.12 [get_ports {x[0]}]
set_input_transition 0.12 [get_ports {y[31]}]
set_input_transition 0.12 [get_ports {y[30]}]
set_input_transition 0.12 [get_ports {y[29]}]
set_input_transition 0.12 [get_ports {y[28]}]
set_input_transition 0.12 [get_ports {y[27]}]
set_input_transition 0.12 [get_ports {y[26]}]
set_input_transition 0.12 [get_ports {y[25]}]
set_input_transition 0.12 [get_ports {y[24]}]
set_input_transition 0.12 [get_ports {y[23]}]
set_input_transition 0.12 [get_ports {y[22]}]
set_input_transition 0.12 [get_ports {y[21]}]
set_input_transition 0.12 [get_ports {y[20]}]
set_input_transition 0.12 [get_ports {y[19]}]
set_input_transition 0.12 [get_ports {y[18]}]
set_input_transition 0.12 [get_ports {y[17]}]
set_input_transition 0.12 [get_ports {y[16]}]
set_input_transition 0.12 [get_ports {y[15]}]
set_input_transition 0.12 [get_ports {y[14]}]
set_input_transition 0.12 [get_ports {y[13]}]
set_input_transition 0.12 [get_ports {y[12]}]
set_input_transition 0.12 [get_ports {y[11]}]
set_input_transition 0.12 [get_ports {y[10]}]
set_input_transition 0.12 [get_ports {y[9]}]
set_input_transition 0.12 [get_ports {y[8]}]
set_input_transition 0.12 [get_ports {y[7]}]
set_input_transition 0.12 [get_ports {y[6]}]
set_input_transition 0.12 [get_ports {y[5]}]
set_input_transition 0.12 [get_ports {y[4]}]
set_input_transition 0.12 [get_ports {y[3]}]
set_input_transition 0.12 [get_ports {y[2]}]
set_input_transition 0.12 [get_ports {y[1]}]
set_input_transition 0.12 [get_ports {y[0]}]
set_wire_load_mode "enclosed"
