
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Sep  3 2024 10:03:19 IST (Sep  3 2024 04:33:19 UTC)

// Verification Directory fv/ksa32 

module ksa32(carryout, sum, a, b, cin);
  input [31:0] a, b;
  input cin;
  output carryout;
  output [31:0] sum;
  wire [31:0] a, b;
  wire cin;
  wire carryout;
  wire [31:0] sum;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_10, n_12, n_14, n_16, n_18, n_20, n_22;
  wire n_24, n_26, n_29, n_34, n_39, n_44, n_45, n_47;
  wire n_48, n_50, n_51, n_53, n_54, n_56, n_57, n_59;
  wire n_60, n_62, n_63, n_65, n_66, n_68, n_69, n_71;
  wire n_72, n_74, n_75, n_77, n_78, n_80, n_81, n_83;
  wire n_84, n_86, n_154, n_157, n_158;
  ADDFX2 g4251__2398(.A (b[31]), .B (a[31]), .CI (n_86), .CO
       (carryout), .S (sum[31]));
  OAI21XL g4252__5107(.A0 (n_83), .A1 (n_84), .B0 (n_3), .Y (n_86));
  CLKXOR2X2 g4253__6260(.A (n_84), .B (n_83), .Y (sum[30]));
  CLKXOR2X2 g4255__4319(.A (n_80), .B (n_81), .Y (sum[29]));
  AOI22XL g4254__8428(.A0 (n_81), .A1 (n_80), .B0 (a[29]), .B1 (b[29]),
       .Y (n_83));
  CLKXOR2X2 g4257__5526(.A (n_77), .B (n_78), .Y (sum[28]));
  OAI21XL g4256__6783(.A0 (n_78), .A1 (n_77), .B0 (n_2), .Y (n_81));
  AOI22XL g4258__3680(.A0 (n_74), .A1 (n_75), .B0 (a[27]), .B1 (b[27]),
       .Y (n_78));
  CLKXOR2X2 g4259__1617(.A (n_75), .B (n_74), .Y (sum[27]));
  CLKXOR2X2 g4261__2802(.A (n_71), .B (n_72), .Y (sum[26]));
  OAI21XL g4260__1705(.A0 (n_72), .A1 (n_71), .B0 (n_5), .Y (n_74));
  AOI22XL g4262__5122(.A0 (n_68), .A1 (n_69), .B0 (a[25]), .B1 (b[25]),
       .Y (n_72));
  CLKXOR2X2 g4263__8246(.A (n_69), .B (n_68), .Y (sum[25]));
  OAI21XL g4264__7098(.A0 (n_65), .A1 (n_66), .B0 (n_1), .Y (n_68));
  CLKXOR2X2 g4265__6131(.A (n_66), .B (n_65), .Y (sum[24]));
  AOI22XL g4266__1881(.A0 (n_62), .A1 (n_63), .B0 (a[23]), .B1 (b[23]),
       .Y (n_65));
  CLKXOR2X2 g4267__5115(.A (n_63), .B (n_62), .Y (sum[23]));
  CLKXOR2X2 g4269__7482(.A (n_59), .B (n_60), .Y (sum[22]));
  OAI21XL g4268__4733(.A0 (n_60), .A1 (n_59), .B0 (n_6), .Y (n_62));
  CLKXOR2X2 g4271__6161(.A (n_56), .B (n_57), .Y (sum[21]));
  AOI22XL g4270__9315(.A0 (n_57), .A1 (n_56), .B0 (a[21]), .B1 (b[21]),
       .Y (n_60));
  OAI21XL g4272__9945(.A0 (n_53), .A1 (n_54), .B0 (n_4), .Y (n_57));
  CLKXOR2X2 g4273__2883(.A (n_54), .B (n_53), .Y (sum[20]));
  AOI22XL g4274__2346(.A0 (n_50), .A1 (n_51), .B0 (a[19]), .B1 (b[19]),
       .Y (n_53));
  CLKXOR2X2 g4275__1666(.A (n_51), .B (n_50), .Y (sum[19]));
  OAI21XL g4276__7410(.A0 (n_47), .A1 (n_48), .B0 (n_0), .Y (n_50));
  CLKXOR2X2 g4277__6417(.A (n_48), .B (n_47), .Y (sum[18]));
  AOI22XL g4278__5477(.A0 (n_44), .A1 (n_45), .B0 (a[17]), .B1 (b[17]),
       .Y (n_47));
  CLKXOR2X2 g4279__2398(.A (n_45), .B (n_44), .Y (sum[17]));
  ADDFX2 g4280__5107(.A (b[16]), .B (a[16]), .CI (n_154), .CO (n_44),
       .S (sum[16]));
  ADDFX2 g4283__8428(.A (b[14]), .B (a[14]), .CI (n_157), .CO (n_39),
       .S (sum[14]));
  ADDFX2 g4286__3680(.A (b[12]), .B (a[12]), .CI (n_158), .CO (n_34),
       .S (sum[12]));
  ADDFX2 g4289__1705(.A (b[10]), .B (a[10]), .CI (n_26), .CO (n_29), .S
       (sum[10]));
  ADDFX2 g4290__5122(.A (b[9]), .B (a[9]), .CI (n_24), .CO (n_26), .S
       (sum[9]));
  ADDFX2 g4291__8246(.A (b[8]), .B (a[8]), .CI (n_22), .CO (n_24), .S
       (sum[8]));
  ADDFX2 g4292__7098(.A (b[7]), .B (a[7]), .CI (n_20), .CO (n_22), .S
       (sum[7]));
  ADDFX2 g4293__6131(.A (b[6]), .B (a[6]), .CI (n_18), .CO (n_20), .S
       (sum[6]));
  ADDFX2 g4294__1881(.A (b[5]), .B (a[5]), .CI (n_16), .CO (n_18), .S
       (sum[5]));
  ADDFX2 g4295__5115(.A (b[4]), .B (a[4]), .CI (n_14), .CO (n_16), .S
       (sum[4]));
  ADDFX2 g4296__7482(.A (b[3]), .B (a[3]), .CI (n_12), .CO (n_14), .S
       (sum[3]));
  ADDFX2 g4297__4733(.A (b[2]), .B (a[2]), .CI (n_10), .CO (n_12), .S
       (sum[2]));
  ADDFX2 g4298__6161(.A (b[1]), .B (a[1]), .CI (n_7), .CO (n_10), .S
       (sum[1]));
  CLKXOR2X2 g4299__9315(.A (n_8), .B (cin), .Y (sum[0]));
  ADDHXL g4300__9945(.A (b[0]), .B (a[0]), .CO (n_7), .S (n_8));
  CLKXOR2X1 g4314__2883(.A (b[17]), .B (a[17]), .Y (n_45));
  XNOR2X1 g4311__2346(.A (b[18]), .B (a[18]), .Y (n_48));
  XNOR2X1 g4312__1666(.A (b[30]), .B (a[30]), .Y (n_84));
  CLKXOR2X1 g4313__7410(.A (b[21]), .B (a[21]), .Y (n_56));
  CLKXOR2X1 g4308__6417(.A (b[19]), .B (a[19]), .Y (n_51));
  CLKXOR2X1 g4304__5477(.A (b[23]), .B (a[23]), .Y (n_63));
  XNOR2X1 g4315__2398(.A (b[28]), .B (a[28]), .Y (n_77));
  XNOR2X1 g4309__4319(.A (b[24]), .B (a[24]), .Y (n_66));
  XNOR2X1 g4307__5526(.A (b[20]), .B (a[20]), .Y (n_54));
  XNOR2X1 g4305__6783(.A (b[22]), .B (a[22]), .Y (n_59));
  CLKXOR2X1 g4310__3680(.A (b[25]), .B (a[25]), .Y (n_69));
  CLKXOR2X1 g4301__1617(.A (b[27]), .B (a[27]), .Y (n_75));
  XNOR2X1 g4306__2802(.A (b[26]), .B (a[26]), .Y (n_71));
  CLKXOR2X1 g4317__1705(.A (b[29]), .B (a[29]), .Y (n_80));
  NAND2XL g4319__5122(.A (b[22]), .B (a[22]), .Y (n_6));
  NAND2XL g4318__8246(.A (b[26]), .B (a[26]), .Y (n_5));
  NAND2XL g4320__7098(.A (b[20]), .B (a[20]), .Y (n_4));
  NAND2XL g4323__6131(.A (b[30]), .B (a[30]), .Y (n_3));
  NAND2XL g4322__1881(.A (b[28]), .B (a[28]), .Y (n_2));
  NAND2XL g4321__5115(.A (b[24]), .B (a[24]), .Y (n_1));
  NAND2XL g4324__7482(.A (b[18]), .B (a[18]), .Y (n_0));
  ADDFX2 g2(.A (b[15]), .B (a[15]), .CI (n_39), .CO (n_154), .S
       (sum[15]));
  ADDFX2 g4325(.A (b[13]), .B (a[13]), .CI (n_34), .CO (n_157), .S
       (sum[13]));
  ADDFX2 g4326(.A (b[11]), .B (a[11]), .CI (n_29), .CO (n_158), .S
       (sum[11]));
endmodule

