
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Sep  3 2024 10:02:27 IST (Sep  3 2024 04:32:27 UTC)

// Verification Directory fv/ksa16 

module ksa16(carryout, sum, a, b, cin);
  input [15:0] a, b;
  input cin;
  output carryout;
  output [15:0] sum;
  wire [15:0] a, b;
  wire cin;
  wire carryout;
  wire [15:0] sum;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_21, n_22, n_24, n_25, n_27, n_28, n_30, n_31;
  wire n_33, n_34, n_36, n_37, n_39, n_40, n_42, n_43;
  wire n_45, n_46, n_48, n_49, n_51;
  CLKXOR2X2 g1232__6260(.A (n_48), .B (n_49), .Y (sum[14]));
  OAI21XL g1231__4319(.A0 (n_49), .A1 (n_48), .B0 (n_5), .Y (n_51));
  AOI22XL g1233__8428(.A0 (n_45), .A1 (n_46), .B0 (a[13]), .B1 (b[13]),
       .Y (n_49));
  CLKXOR2X2 g1234__5526(.A (n_46), .B (n_45), .Y (sum[13]));
  OAI21XL g1235__6783(.A0 (n_42), .A1 (n_43), .B0 (n_4), .Y (n_45));
  CLKXOR2X2 g1236__3680(.A (n_43), .B (n_42), .Y (sum[12]));
  CLKXOR2X2 g1238__1617(.A (n_39), .B (n_40), .Y (sum[11]));
  AOI22XL g1237__2802(.A0 (n_40), .A1 (n_39), .B0 (a[11]), .B1 (b[11]),
       .Y (n_42));
  CLKXOR2X2 g1240__1705(.A (n_36), .B (n_37), .Y (sum[10]));
  OAI21XL g1239__5122(.A0 (n_37), .A1 (n_36), .B0 (n_0), .Y (n_40));
  CLKXOR2X2 g1242__8246(.A (n_33), .B (n_34), .Y (sum[9]));
  AOI22XL g1241__7098(.A0 (n_34), .A1 (n_33), .B0 (a[9]), .B1 (b[9]),
       .Y (n_37));
  CLKXOR2X2 g1244__6131(.A (n_30), .B (n_31), .Y (sum[8]));
  OAI21XL g1243__1881(.A0 (n_31), .A1 (n_30), .B0 (n_3), .Y (n_34));
  CLKXOR2X2 g1246__5115(.A (n_27), .B (n_28), .Y (sum[7]));
  AOI22XL g1245__7482(.A0 (n_28), .A1 (n_27), .B0 (a[7]), .B1 (b[7]),
       .Y (n_31));
  CLKXOR2X2 g1248__4733(.A (n_24), .B (n_25), .Y (sum[6]));
  OAI21XL g1247__6161(.A0 (n_25), .A1 (n_24), .B0 (n_2), .Y (n_28));
  AOI22XL g1249__9315(.A0 (n_21), .A1 (n_22), .B0 (a[5]), .B1 (b[5]),
       .Y (n_25));
  CLKXOR2X2 g1250__9945(.A (n_22), .B (n_21), .Y (sum[5]));
  OAI21XL g1251__2883(.A0 (n_18), .A1 (n_19), .B0 (n_1), .Y (n_21));
  CLKXOR2X2 g1252__2346(.A (n_19), .B (n_18), .Y (sum[4]));
  AOI22XL g1253__1666(.A0 (n_15), .A1 (n_16), .B0 (a[3]), .B1 (b[3]),
       .Y (n_18));
  CLKXOR2X2 g1254__7410(.A (n_16), .B (n_15), .Y (sum[3]));
  CLKXOR2X2 g1256__6417(.A (n_12), .B (n_13), .Y (sum[2]));
  OAI21XL g1255__5477(.A0 (n_13), .A1 (n_12), .B0 (n_6), .Y (n_15));
  CLKXOR2X2 g1258__2398(.A (n_9), .B (n_8), .Y (sum[1]));
  CLKXOR2X2 g1259__5107(.A (n_7), .B (cin), .Y (sum[0]));
  AOI22XL g1257__6260(.A0 (n_9), .A1 (n_8), .B0 (a[1]), .B1 (b[1]), .Y
       (n_13));
  ADDHXL g1260__4319(.A (b[0]), .B (a[0]), .CO (n_8), .S (n_7));
  XNOR2X1 g1273__8428(.A (b[12]), .B (a[12]), .Y (n_43));
  XNOR2X1 g1267__5526(.A (b[6]), .B (a[6]), .Y (n_24));
  CLKXOR2X1 g1269__6783(.A (b[3]), .B (a[3]), .Y (n_16));
  CLKXOR2X1 g1270__3680(.A (b[9]), .B (a[9]), .Y (n_33));
  XNOR2X1 g1271__1617(.A (b[2]), .B (a[2]), .Y (n_12));
  CLKXOR2X1 g1265__1705(.A (b[13]), .B (a[13]), .Y (n_46));
  XNOR2X1 g1261__5122(.A (b[4]), .B (a[4]), .Y (n_19));
  XNOR2X1 g1275__8246(.A (b[8]), .B (a[8]), .Y (n_30));
  XNOR2X1 g1268__7098(.A (b[14]), .B (a[14]), .Y (n_48));
  XNOR2X1 g1266__6131(.A (b[10]), .B (a[10]), .Y (n_36));
  CLKXOR2X1 g1274__1881(.A (b[1]), .B (a[1]), .Y (n_9));
  CLKXOR2X1 g1262__5115(.A (b[7]), .B (a[7]), .Y (n_27));
  CLKXOR2X1 g1263__7482(.A (b[5]), .B (a[5]), .Y (n_22));
  CLKXOR2X1 g1264__4733(.A (b[11]), .B (a[11]), .Y (n_39));
  NAND2XL g1282__6161(.A (b[2]), .B (a[2]), .Y (n_6));
  NAND2XL g1276__9315(.A (b[14]), .B (a[14]), .Y (n_5));
  NAND2XL g1277__9945(.A (b[12]), .B (a[12]), .Y (n_4));
  NAND2XL g1279__2883(.A (b[8]), .B (a[8]), .Y (n_3));
  NAND2XL g1278__2346(.A (b[6]), .B (a[6]), .Y (n_2));
  NAND2XL g1280__1666(.A (b[4]), .B (a[4]), .Y (n_1));
  NAND2XL g1281__7410(.A (b[10]), .B (a[10]), .Y (n_0));
  ADDFX2 g2(.A (b[15]), .B (a[15]), .CI (n_51), .CO (carryout), .S
       (sum[15]));
endmodule

