
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Sep  3 2024 09:46:40 IST (Sep  3 2024 04:16:40 UTC)

// Verification Directory fv/ksa8 

module ksa8(carryout, sum, a, b, cin);
  input [7:0] a, b;
  input cin;
  output carryout;
  output [7:0] sum;
  wire [7:0] a, b;
  wire cin;
  wire carryout;
  wire [7:0] sum;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_8, n_9;
  wire n_11, n_12, n_14, n_15, n_17, n_18, n_20, n_21;
  wire n_23;
  CLKXOR2X2 g551__6260(.A (n_20), .B (n_21), .Y (sum[6]));
  OAI21XL g550__4319(.A0 (n_21), .A1 (n_20), .B0 (n_1), .Y (n_23));
  AOI22XL g552__8428(.A0 (n_17), .A1 (n_18), .B0 (a[5]), .B1 (b[5]), .Y
       (n_21));
  CLKXOR2X2 g553__5526(.A (n_18), .B (n_17), .Y (sum[5]));
  OAI21XL g554__6783(.A0 (n_14), .A1 (n_15), .B0 (n_0), .Y (n_17));
  CLKXOR2X2 g555__3680(.A (n_15), .B (n_14), .Y (sum[4]));
  AOI22XL g556__1617(.A0 (n_11), .A1 (n_12), .B0 (a[3]), .B1 (b[3]), .Y
       (n_14));
  CLKXOR2X2 g557__2802(.A (n_12), .B (n_11), .Y (sum[3]));
  CLKXOR2X2 g559__1705(.A (n_8), .B (n_9), .Y (sum[2]));
  OAI21XL g558__5122(.A0 (n_9), .A1 (n_8), .B0 (n_2), .Y (n_11));
  AOI22XL g560__8246(.A0 (n_6), .A1 (n_5), .B0 (a[1]), .B1 (b[1]), .Y
       (n_9));
  CLKXOR2X2 g561__7098(.A (n_6), .B (n_5), .Y (sum[1]));
  CLKXOR2X2 g562__6131(.A (n_3), .B (cin), .Y (sum[0]));
  ADDHXL g563__1881(.A (b[0]), .B (a[0]), .CO (n_5), .S (n_3));
  CLKXOR2X1 g567__5115(.A (b[1]), .B (a[1]), .Y (n_6));
  XNOR2X1 g566__7482(.A (b[2]), .B (a[2]), .Y (n_8));
  XNOR2X1 g568__4733(.A (b[6]), .B (a[6]), .Y (n_20));
  CLKXOR2X1 g564__6161(.A (b[3]), .B (a[3]), .Y (n_12));
  XNOR2X1 g570__9315(.A (b[4]), .B (a[4]), .Y (n_15));
  CLKXOR2X1 g565__2883(.A (b[5]), .B (a[5]), .Y (n_18));
  NAND2XL g571__2346(.A (b[2]), .B (a[2]), .Y (n_2));
  NAND2XL g572__1666(.A (b[6]), .B (a[6]), .Y (n_1));
  NAND2XL g573__7410(.A (b[4]), .B (a[4]), .Y (n_0));
  ADDFX2 g2(.A (b[7]), .B (a[7]), .CI (n_23), .CO (carryout), .S
       (sum[7]));
endmodule

